using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class RelationshipDisplay : MonoBehaviour
{
    [Header("‘")] public string country;
    [Header("—FD“x")] public float friendshipLevel;
    [Header("ŒoÏ—Í")] public float economicPower;
    [Header("ŒR–—Í")] public float militaryPower;
    [Header("–fˆÕ•i")] public string tradeGoods;
    [Header("–fˆÕó‹µ")] public string tradeSituation;

    private string country2;//‘
    private float friendshipLevel2;//—FD“x
    private float economicPower2;//ŒoÏ—Í
    private float militaryPower2;//ŒR–—Í
    private string tradeGoods2;//–fˆÕ•i
    private string tradeSituation2;//–fˆÕó‹µ

    Text RelationshipText;

    // Start is called before the first frame update
    void Start()
    {
        RelationshipText = this.GetComponent<Text>();
    }

    // Update is called once per frame
    void Update()
    {
        if(country != country2)
        {
            country2 = country;
            ClickButtonRelationshipText();
        }
        else if(friendshipLevel != friendshipLevel2)
        {
            friendshipLevel2 = friendshipLevel;
            ClickButtonRelationshipText();
        }
        else if(economicPower != economicPower2)
        {
            economicPower2 = economicPower;
            ClickButtonRelationshipText();
        }
        else if (militaryPower != militaryPower2)
        {
            militaryPower2 = militaryPower;
            ClickButtonRelationshipText();
        }
        else if (tradeGoods != tradeGoods2)
        {
            tradeGoods2 = tradeGoods;
            ClickButtonRelationshipText();
        }
        else if(tradeSituation != tradeSituation2)
        {
            tradeSituation2 = tradeSituation;
            ClickButtonRelationshipText();
        }
    }

    //ŠÖŒW’l‚ğ•\¦‚·‚éŠÖ”
    public void ClickButtonRelationshipText()
    {

        RelationshipText.text = "ŠÖŒW’l" + "\n" +
            "‘F" + country + "\n" +
            "—FD“xF" + friendshipLevel + "%" + "\n" +
            "ŒoÏ—ÍF" + economicPower + "ˆÊ" + "\n" +
            "ŒR–—ÍF" + militaryPower + "ˆÊ" + "\n" +
            "–fˆÕ•iF" + tradeGoods + "\n" +
            "–fˆÕó‹µF" + tradeSituation;
    }
}
